default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  host: localhost
  port: 3306
  username: root
  password: root

development:
  <<: *default
  database: aw-editorialhands

test:
  <<: *default
  database: aw-editorialhands_test
