NullJob:
  at: '3001/01/01'
  description: '空のjob（疎通確認用）'
AddTempSeriesDeckDataJob:
  at: '3001/01/01'
  description: 'シリーズデッキの仮データを投入する https://github.com/d7lab/aw-editorialhands/issues/965'
FillPlaylistDefaultValueJob:
  at: '3001/01/01'
  description: '全プレイリストの publish_level を full にし、layout_pattern を summary にする'
OpenAllSeriesDecksJob:
  at: '3001/01/01'
  description: '全シリーズデッキを公開状態にする'
RemoveMissingArticleImagesJob:
  every: '24h'
  description: 'プレイリストに紐付いていない古い記事画像の削除'
SendUpdateNotificationJob:
  every: '1h'
  description: '更新通知メッセージを送信する'
SaveAllPlaylistJob:
  at: '3001/01/01'
  description: '全プレイリストをsaveする'
