default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || 10  %>
  database: <%= ENV['DB_NAME'] || 'aw_editorialhands_development' %>
  username: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV["DB_HOST"] %>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  reconnect: true

development:
  <<: *default
  port: <%= ENV['DB_PORT'] %> # 未設定でOK。host側からdocker-composeのdbを利用する場合など「4306」を設定する

test:
  <<: *default
  database: aw_editorialhands_test

production:
  <<: *default
  database: aw_editorialhands_production
  url: <%= ENV['DATABASE_URL'] %>
