version: "3"

services:
  frontend:
    build:
      context: ./frontend-edge
      dockerfile: Dockerfile
    tty: true
    command: yarn dev
    environment:
      API_URL: "http://web:3000"
    volumes:
      - ./frontend-edge:/app
    ports:
      - 8080:3000
    depends_on:
      - web
      - db
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --ft_min_word_len=1
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: ./api-eh
      dockerfile: Dockerfile
    command: bash -c "rm -f ./tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    ports:
      - 8888:3000
    environment:
      - DB_HOST=db
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    volumes:
      - ./api-eh:/app
      - bundle:/bundle
    tmpfs:
      - /tmp
  sidekiq:
    build:
      context: ./api-eh
      dockerfile: Dockerfile
    command: bash -c "mkdir -p tmp & bundle exec sidekiq"
    environment:
      - DB_HOST=db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    volumes:
      - ./api-eh:/app
      - bundle:/bundle
    tmpfs:
      - /tmp
  redis:
    image: redis:6.2-alpine
  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    command: /bin/sh -c "sleep 120;npx cypress run --browser chrome --headless"
    depends_on:
      - web
      - frontend
      - db
      - sidekiq
      - redis
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
      - CYPRESS_browser=chrome
      - CYPRESS_screenshotsFolder=/results/screenshots
      - CYPRESS_videosFolder=/results/videos
      - CYPRESS_API_URL=http://web:3000
    volumes:
      - ./e2e/cypress:/app/cypress
      - ./e2e/cypress.json:/app/cypress.json
      - ./e2e/results:/results
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
