version: "3"
services:
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
  web:
    build: .
    command: bash -c "bundle exec jets server --host 0.0.0.0"
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "8888:8888"
    environment:
      - DB_HOST=db
      - JETS_ENV=$JETS_ENV
      - JETS_AGREE=$JETS_AGREE

    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
