# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jets', '~> 2.3', submodules: true

gem 'acts_as_list'
gem 'chroma'
gem 'colormath'
gem 'counter_culture'
gem 'discard'
gem 'faraday'
gem 'faraday_middleware'
gem 'fastimage'
gem 'friendly_id'
gem 'image_processing'
gem 'jbuilder'
gem 'jwt'
gem 'kaminari'
gem 'multi_json'
gem 'mysql2', '~> 0.5.2'
gem 'ostruct', '0.1.0'
gem 'redcarpet'
gem 'sanitize'
gem 'shrine', github: 'shrinerb/shrine'
gem 'slack-incoming-webhooks'

# development and test groups are not bundled as part of the deployment
group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'cody'
  gem 'pipedream'
  gem 'pry-byebug'
  gem 'puma'
  gem 'rack'
  gem 'rubocop', require: false
  gem 'shotgun'
end

group :test do
  gem 'capybara'
  gem 'launchy'
  # rspec test group only or we get the "irb: warn: can't alias context from irb_context warning"
  # when starting jets console
  gem 'database_cleaner-active_record'
  gem 'factory_bot'
  gem 'rspec'
end
