// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import KeyColorController from "./key_color_controller"
application.register("key-color", KeyColorController)
