AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation for aw-editorialhands db/security groups"
Parameters:
  VPC:
    Type: String
    Default: vpc-e126db85
  PrivateSubnetA1:
    Type: String
    Default: subnet-6377c515
  PrivateSubnetC1:
    Type: String
    Default: subnet-d1c51189
  PrivateSubnetGroups:
    Type: String
    Default: aw-aurora-subnet-group

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: "aw-editorialhands-lambda-sg"

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPC
      GroupDescription: "aw-editorialhands-db-sg"
      SecurityGroupIngress:
        - SourceSecurityGroupId: !Ref LambdaSecurityGroup
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306

  DBClusterParamGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: aurora cluster parameter group
      Family: aurora-mysql5.7
      Parameters:
        character_set_server: utf8mb4
        character_set_client: utf8mb4
        character_set_connection: utf8mb4
        character_set_results: utf8mb4
        character_set_database: utf8mb4
        character_set_filesystem: binary
        collation_connection: utf8mb4_general_ci

  DbCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: editorialhands
      MasterUserPassword: 3d1t0rialhands
      Engine: aurora-mysql
      DBSubnetGroupName: !Ref PrivateSubnetGroups
      DBClusterParameterGroupName: !Ref DBClusterParamGroup
      VpcSecurityGroupIds:
        - Ref: DBSecurityGroup
      Tags:
        - Key: Name
          Value: aw-editorialhands-aurora-db-cluster

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref PrivateSubnetGroups
      Engine: aurora-mysql
      DBClusterIdentifier: !Ref DbCluster
      DBInstanceIdentifier: aw-editorialhands-aurora-db-instance
      DBInstanceClass: db.t3.small
      Tags:
        - Key: Name
          Value: aw-editorialhands-aurora-db-instance
