env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:cypress/recommended
  - plugin:@typescript-eslint/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - 'cypress'
  - '@typescript-eslint'
rules:
  semi:
    - error
    - never
root: true
