version: '3'
services:
  terraform:
    image: hashicorp/terraform:1.1.5
    volumes:
      - ..:/app
    command: bash
    environment:
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
