require: rubocop-rspec

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*.rb
    - db/fixtures/**/*.rb
    - spec/*_helper.rb
    - bin/**/*
    - tmp/**/*
    - local_modules/**/*
    - node_modules/**/*
    - vendor/**/*
    - infra/**/*
    - lambda/**/vendor/**/*
  TargetRubyVersion: 3.0

Naming/AccessorMethodName:
  Enabled: false # set_ get_ メソッド名を許可

Style/AccessorGrouping:
  Enabled: true

Style/ArgumentsForwarding:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/AsciiComments:
  Enabled: false # 日本語コメントを許可

Style/BisectedAttrAccessor:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - spec/**/*

Style/CaseLikeIf:
  Enabled: true

Style/ClassAndModuleChildren: # Module/Classのネストを許可
  Enabled: false

Style/ClassEqualityComparison:
  Enabled: true

Style/CollectionCompact:
  Enabled: true

Style/CombinableLoops:
  Enabled: true

Style/Documentation:
  Enabled: false # ドキュメンテーション用のコメントを必須にしない

Style/DocumentDynamicEvalDefinition:
  Enabled: true

Style/EndlessMethod:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashExcept:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/IfWithBooleanLiteralBranches:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: true

Style/NegatedIfElseCondition:
  Enabled: true

Style/NilLambda:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/RedundantSelfAssignment:
  Enabled: true

Style/RescueStandardError: # rescueでStandardErrorのみを補足する場合は省略する
  EnforcedStyle: "implicit"

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Style/SwapValues:
  Enabled: true

Metrics/MethodLength: # メソッドの行数
  Max: 15 # デフォルトは10

Metrics/AbcSize:
  Max: 17 # デフォルトは15

Metrics/BlockLength: # ブロックの行数
  Exclude:
    - lib/tasks/*.rake
    - spec/**/*.rb
    - config/routes.rb
    - config/environments/**/*

Metrics/ClassLength:
  Exclude:
    - lib/tasks/*.rake
    - spec/**/*.rb
    - config/routes.rb
    - config/environments/**/*
    - app/models/series.rb
  Max: 200

Layout/BeginEndAlignment:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 120

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

Metrics/ModuleLength:
  Max: 200

Naming/PredicateName:
  Enabled: false # has_, is_, have_ など,特定の文字列で始まるメソッド名を許可

Naming/MethodParameterName:
  Enabled: false # メソッドの引数名の最小文字数制限

Lint/AmbiguousAssignment:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/DeprecatedConstants:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: true

Lint/DuplicateBranch:
  Enabled: true

Lint/DuplicateRequire:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyBlock:
  Enabled: true

Lint/EmptyClass:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: true

Lint/IdentityComparison:
  Enabled: true

Lint/LambdaWithoutLiteralBlock:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/NoReturnInBeginEndBlocks:
  Enabled: true

Lint/NumberedParameterAssignment:
  Enabled: true

Lint/OrAssignmentToConstant:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/RedundantDirGlobSort:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/SymbolConversion:
  Enabled: true

Lint/ToEnumArguments:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/TripleQuotes:
  Enabled: true

Lint/UnexpectedBlockArity:
  Enabled: true

Lint/UnmodifiedReduceAccumulator:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

RSpec/NestedGroups:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

RSpec/MessageChain:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
