version: "3"
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --ft_min_word_len=1
    volumes:
      - db-data:/var/lib/mysql
  rails:
    build: .
    command: bash -c "rm -f ./tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - "8888:3000"
    environment:
      - DB_HOST=db
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
    tty: true
    stdin_open: true
  redis:
    image: redis:6.2-alpine
    ports:
      - "8379:6379"
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
