source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '>= 3.0.0'

gem 'rails', '~> 7.0.3'

gem 'jbuilder'
gem 'mysql2'
gem 'puma', '~> 5.0'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 5.0'

gem 'bootsnap', require: false

gem 'acts_as_list'
gem 'asset_sync'
gem 'aws-sdk-sns'
gem 'chroma'
gem 'colormath'
gem 'counter_culture'
gem 'discard'
gem 'exception_notification'
gem 'faraday'
gem 'faraday_middleware'
gem 'fastimage'
gem 'fog-aws'
gem 'friendly_id'
gem 'image_processing'
gem 'jwt'
gem 'kaminari'
gem 'multi_json'
gem 'ogp'
gem 'redis'
gem 'request_store'
gem 'shrine'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'sidekiq-worker-killer'
gem 'slack-incoming-webhooks'
gem 'slack-notifier'
gem 'stimulus-rails'
gem 'tailwindcss-rails'
gem 'view_component'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'cody'
  gem 'pipedream'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'rubocop'
end

group :development do
  gem 'listen'
  gem 'rack-mini-profiler'
  gem 'spring'
  gem 'web-console'
end

group :test do
  gem 'database_cleaner-active_record'
  gem 'factory_bot'
  gem 'rspec-openapi'
  gem 'rubocop-rspec'
  gem 'vcr'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
