name: Staging Release
on: [workflow_dispatch]
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    name: create_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create a release pull request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: staging
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_TEMPLATE: .git-pr-template
        run: |
          sudo gem install git-pr-release
          git-pr-release
