name: Test

on: [push]

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker compose
        run: docker-compose build
      - name: Yarn install for dev
        run: docker-compose run frontend yarn install
      - name: Run Lint
        run: docker-compose run frontend yarn lint
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,message,author
          author_name: lint-job
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
