name: Test for backend

on:
  push:
    paths:
      - "api-eh/**"
      - ".github/workflows/test-backend.yml"

jobs:
  lint-and-test:
    env:
      RAILS_ENV: test
      working-directory: ./api-eh
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker compose
        run: docker-compose build
        working-directory: ${{env.working-directory}}
      - name: Run setup
        run: docker-compose run rails bin/setup
        working-directory: ${{env.working-directory}}
      - name: Run Lint
        run: docker-compose run rails bundle exec rubocop
        working-directory: ${{env.working-directory}}
      - name: Run Rspec
        run: docker-compose run rails bundle exec rspec
        working-directory: ${{env.working-directory}}
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,message,author
          author_name: lint-job
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
