name: Test for backend

on:
  push:
    paths:
      - "api-eh/**"
      - ".github/workflows/ci-backend.yml"

env:
  RAILS_ENV: test
  DB_NAME: editorialhands_test

defaults:
  run:
    working-directory: api-eh

jobs:
  prepare:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: ./api-eh/yarn.lock
      - name: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
          working-directory: ./api-eh
      - run: bundle exec rubocop

  lint-and-test:
    runs-on: ubuntu-18.04
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        parallelism: [ 5 ]
        id: [ 0,1,2,3,4 ]
    steps:
      - uses: actions/checkout@v1
      - name: ja_JP.UTF-8
        run: |
          sudo locale-gen ja_JP.UTF-8
          sudo update-locale LANG=ja_JP.UTF-8
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install ghostscript fonts-vlgothic
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: ./api-eh/yarn.lock
      - name: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
          bundler-cache: true
          working-directory: ./api-eh
      - name: Database prepare
        run: |
          mysql --version
          sudo service mysql start
          cp -v config/database.ci.yml config/database.yml
          bin/rails db:prepare
      - run: bin/test_splitter -p ${{ matrix.parallelism }} -i ${{ matrix.id }} | xargs bundle exec rspec
      - uses: actions/upload-artifact@v2
        with:
          name: test-results
          retention-days: 7
          path: |
            api-eh/log/**/*
            api-eh/tmp/screenshots/**/*
            api-eh/tmp/capybara/**/*
        if: always()
