name: Test for frontend

on:
  push:
    paths:
      - 'frontend-edge/**'
      - '.github/workflows/test-frontend-edge.yml'

jobs:
  lint-and-test:
    defaults:
      run:
        working-directory: ./frontend-edge
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: frontend-edge/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test run
  storybook:
    defaults:
      run:
        working-directory: ./frontend-edge
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: frontend-edge/pnpm-lock.yaml
      - run: pnpm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Storybook tests
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"
          export DEBUG=pw:browser*
          pnpm test-storybook:ci
