name: E2E Test

on: [push]

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    timeout-minutes: 35
    steps:
      - uses: actions/checkout@v3
      - run: docker version
      - name: Setup docker compose
        uses: yu-ichiro/spin-up-docker-compose-action@v1
        with:
          file: ./docker-compose.yml
      - name: frontend yarn install
        run: docker-compose run frontend yarn install
      - name: rails setup
        run: docker-compose run web bin/setup
      - name: run cypress
        run: docker-compose up --abort-on-container-exit --exit-code-from e2e
