name: E2E Test

on: [push]

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose pull
      - name: Build the Docker compose
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: docker-compose build --parallel
      - name: frontend yarn install
        run: docker-compose run frontend yarn install
      - name: rails setup
        run: docker-compose run web bin/setup
      - name: run cypress
        run: docker-compose up --abort-on-container-exit --exit-code-from e2e
